#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=199
STOP=01
 
start_service() {
  procd_open_instance
  procd_set_param command /root/start_proxy.sh
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
  
}

stop_service() {
  killall /root/clash
  nft delete table clash_proxy
  ip rule del fwmark 666 lookup 666
  ip route del local 0.0.0.0/0 dev lo table 666
  echo "clash stopped"
}

reload_service() {
  stop_service
  start_service
}