connections {
  rw {
    version = 2
    # proposals=aes256-sha256-modp2048,aes256-sha1-modp1024
    local {
      auth = psk
      id = %any
    }
    remote {
      id = %any
      auth = psk
    }
    children {
      android {
        local_ts = 0.0.0.0/0
        remote_ts = 10.10.30.0/24
	    updown = /usr/lib/ipsec/_updown iptables
	    hostaccess = yes
        mode = tunnel
      }
    }
    pools = vpn-pool
  }
}

pools {
  vpn-pool {
    # 分配给客户端的 IP 范围
    addrs = 10.10.30.0/24
    # 给客户端指定 DNS 服务器
    dns = 192.168.2.1
  }
}

secrets {
  # PSK 密钥
  ike-android {
    secret = share_psk  # 密钥（无特殊字符可省略引号）
  }
}

# Include config snippets
include conf.d/*.conf

