connections {
  rw {
    version = 2
    # For windows builtin vpn client
    # proposals=aes256-sha256-modp2048,aes256-sha1-modp1024
    local {
      auth = psk
      # Sep 04 21:54:31 debian charon-systemd[712]: looking for peer configs matching 192.168.11.120[192.168.11.120]...192.168.11.171[abc]
      id = %any
    }
    remote {
      auth = psk
      # Sep 04 21:54:31 debian charon-systemd[712]: looking for peer configs matching 192.168.11.120[192.168.11.120]...192.168.11.171[abc]
      # id 对应 Android VPN 的 "IPSec 标识符"
      id = %any
    }
    children {
      android {
        # 当 VPN 网关收到一个数据包时，用remote_ts匹配源地址，用local_ts匹配目的地址
        # 理论上，VPN 网关会和客户端协商，网关的 local_ts 和 客户端的 remote_ts 取交集。
        # CHECK: 但 Android builtin VPN 不支持协商，只能写死。是这样吗？？?
        local_ts = 0.0.0.0/0
        remote_ts = 10.10.30.0/24
	      updown = /usr/lib/ipsec/_updown iptables
	      hostaccess = yes
        mode = tunnel
      }
    }
    pools = vpn-pool
  }
}

pools {
  vpn-pool {
    # 分配给客户端的 IP 范围
    addrs = 10.10.30.0/24
    # 给客户端指定 DNS 服务器
    dns = 192.168.11.1
  }
}

secrets {
  # PSK 密钥
  # ike-<suffix> 这个后缀好像没用？

  # this PSK will be used for any identity if there is no better match
  # because there is no "id" field in this section
  ike-android {
    secret = share_psk  # 密钥（无特殊字符可省略引号）
  }
}

# Include config snippets
include conf.d/*.conf

